services:
  - type: web
    name: sweetlab
    env: node
    plan: free
    buildCommand: cd frontend && npm ci && npm run build:prod && cd ../backend && npm ci
    startCommand: cd backend && node src/server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://mmvolcan_db_user:Albert$1988@swwetlab.uzpk1qs.mongodb.net/?appName=SwwetLab
        scope: build,runtime
      - key: NODE_ENV
        value: ${NODE_ENV}
      - key: PORT
        value: 4000
