services:
  - type: web
    name: sweetlab
    env: node
    plan: free
    buildCommand: cd frontend && npm install && npm run build:prod && cd ../backend && npm install && echo "Build completed successfully"
    startCommand: cd backend && node src/server.js
    envVars:
      - key: MONGO_URI
        scope: build,runtime
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
